### ISSUE TITLE
The Curse of the Blind Stalker - Czech translate

### ISSUE THREAD

**Issue by LabBrab** [vidimus/DomeAcolyte#2]
Hi, I translated the "The Curse of the Blind Stalker" into Czechlanguage. Can translation be added to valkyrie? Thanks
[Localization.Czech.txt](https://github.com/user-attachments/files/17044732/Localization.Czech.txt)

**Comment by vidimus** [comment]
Hello, @LabBrab.

Thanks for translating the scenario into Czech. I will update the scenario with your translation.

**Comment by vidimus** [comment]
![imagen](https://github.com/user-attachments/assets/f59b42d6-5d94-4d06-8388-3c5dd2102d38)

Done! It should be available within an hour.
